### ISSUE TITLE
Bug in countdown timer, If count down time is more than 24 hours away.

### ISSUE THREAD

**Issue by warunacds** [mineschan/MZTimerLabel#22]
I experience there is a bug in countdown timer, if the count down date time is more than 24 hours away from current time.  For example if you pass, [timerLabel setCountDownTime:3600*26] . It will start counting down for 2 hours.

**Comment by CavalcanteLeo** [comment]
- (NSString*)timerLabel:(MZTimerLabel *)timerLabel customTextToDisplayAtTime:(NSTimeInterval)time{
        int second = (int)time  % 60;
        int minute = ((int)time / 60) % 60;
        int hours = ((int)time / 3600) % 24;
        int days = time / (3600 * 24);
        
        if (days > 0) {
            return [NSString stringWithFormat:@"%d : %02d : %02d : %02d",days,hours,minute,second];
    
        }  else if (hours > 0) {
            return [NSString stringWithFormat:@"%d : %02d : %02d",hours,minute,second];
     
        } else if (minute > 0) {
            return [NSString stringWithFormat:@"%d : %02d",minute,second];
        
        } else if (second > 0) {
            return [NSString stringWithFormat:@"%02d",second];

        } else {
            return nil;
        }
    }
