### ISSUE TITLE
How to get countedTime in milliSeconds?

### ISSUE THREAD

**Issue by RMK19** [mineschan/MZTimerLabel#39]
Can you add  a option for getting the counted time in milliseconds

**Comment by mineschan** [comment]
HI @RMK19 

All the time related values MZTimerLabel returns are in `NSTimeInterval`. Which is a double with sub-millisecond accuracy.

I've done a google search for you, hope it helps.
http://stackoverflow.com/questions/889380/how-can-i-get-a-precise-time-for-example-in-milliseconds-in-objective-c
