### ISSUE TITLE
Edit Timer

### ISSUE THREAD

**Issue by adamrushy** [mineschan/MZTimerLabel#4]
Hello, 

What is the best way to edit the timer.

For example we have a timer running and then a user can tap and edit the current time displayed. I edit the label and start but it starts from the previous time.

I have tried "setStopWatch" but it only accepts NSTimeInterval, is their a quick way to edit the timer?

**Comment by hegazy** [comment]
Let's suppose we are on the timer mode! What is the best way to implement that?

**Comment by mineschan** [comment]
There are four setter methods. Use one of them that suit your need, in your case @hegazy 
Will be `-(void)setCountDownTime:(NSTimeInterval)time;`

```
/*--------Setter methods*/
-(void)setCountDownTime:(NSTimeInterval)time;
-(void)setStopWatchTime:(NSTimeInterval)time;
-(void)setCountDownToDate:(NSDate*)date;
-(void)addTimeCountedByTime:(NSTimeInterval)timeToAdd;
```

but remember to convert the displaying time to NSTimeInterval first.
