### ISSUE TITLE
Hours showing 24+

### ISSUE THREAD

**Issue by shreddymunster** [mineschan/MZTimerLabel#40]
First off, great pod! Works like a champ.

I have the countdown timer displaying days, hours, minutes, and secs. All of the time formats work except for the Hours, it displays over 24 hours. Do I need to set the max value for the Hours or is there something I might be missing? 

![screen shot 2015-03-04 at 10 42 44 am](https://cloud.githubusercontent.com/assets/1390055/6486778/3c91542a-c25b-11e4-9a3f-fd804c904b6f.png)

**Comment by shreddymunster** [comment]
I sorted it out.

Changed var hours to:
var hours = Int(time) / 3600 % 24

**Comment by mineschan** [comment]
Thanks and glad you got it sorted out~
