### ISSUE TITLE
2 Timer labels delay

### ISSUE THREAD

**Issue by Pades9** [mineschan/MZTimerLabel#41]
Hi,

in my app I have 2 timer labels(countdown). I pause timers and resume few times. After 2 minutes it is delay first timer has about 1 second more. Where can be the problem?

**Comment by mineschan** [comment]
Hi @Pades9 

For this issues, are they (2times) serving the same purpose which means they should be sync?
Currently MZTimerLabel have no sync function for multiple times,
but you may try this workaround and see if this solve your problem.

Every time before you resume, call `- (NSTimeInterval)getTimeRemaining;` of the first label, then use `-(void)setCountDownTime:(NSTimeInterval)time;` to set the time of second label again.

Let me know, as this is only a workaround, so it might cause the values return from the delegate gone wrong.
