### ISSUE TITLE
Timer Counting Up

### ISSUE THREAD

**Issue by rsickles** [mineschan/MZTimerLabel#42]
I create the timer and call...
self.countdown.setCountDownTime(60)
self.countdown.start()

but the timer label starts at 1 minute then starts to count up. Any help?

**Comment by Zhukn1** [comment]
Try checking the `MZTimerLabelType`. It should be set to `MZTimerLabelTypeTimer`

**Comment by rsickles** [comment]
Do you know how I would do so in Swift?

**Comment by Zhukn1** [comment]
Just make a bridging header to this Pod or fork it and make a Swift version:)

**Comment by rsickles** [comment]
Great, I got it to work using the bridging header. Thanks!

**Comment by Zhukn1** [comment]
👍
