### ISSUE TITLE
Zombie, memory leaks

### ISSUE THREAD

**Issue by sirljan** [mineschan/MZTimerLabel#43]
When you create instance of MZTimerLabel and it is not added as subview (You just create instance and then set timeLabel), removeFromSuperview is not fired > timer is not invalidated and instance stays in memory.

**Comment by liuxuan30** [comment]
Is this true till now?

**Comment by liuxuan30** [comment]
looks like it's true,
```Objective-C
#pragma mark - Cleanup

- (void) removeFromSuperview {
    if (_timer) {
        [_timer invalidate];
        _timer = nil;
    }
    
    [super removeFromSuperview];
}
```
however the MZTimerLabel is not added in any views.

**Comment by mommyme** [comment]
Still an issue?
