### ISSUE TITLE
Countdown not working for more than 24 hours

### ISSUE THREAD

**Issue by Syed-Muhammad-Fakhir** [mineschan/MZTimerLabel#45]
Its not working in this scenario, please assist.

MZTimerLabel *timer = [[MZTimerLabel alloc] initWithLabel:someLabel andTimerType:MZTimerLabelTypeTimer];
    [timer setShouldCountBeyondHHLimit:YES];
    [timer setCountDownTime:3600 * 50];
    [timer start];

**Comment by Syed-Muhammad-Fakhir** [comment]
Could be able to work it around by checking issue#22.

**Comment by mineschan** [comment]
Sorry but my bad for not implemented the logic for timer.

Modify line 362 of MZTimerLabel.m to 
```
int hours = (_timerType == MZTimerLabelTypeStopWatch)? ([self getTimeCounted] / 3600) : ([self getTimeRemaining] / 3600);
```
and it will work. Will commit to the next version. Thanks!

**Comment by Syed-Muhammad-Fakhir** [comment]
Alright, thanks.
