### ISSUE TITLE
Feature request: blinking colon

### ISSUE THREAD

**Issue by to83** [mineschan/MZTimerLabel#50]
Hi,

I am using a custom timeFormat (HH:mm).

So there is not much happening for at least 60 seconds. So I was thinking, it would be cool if the colon could be blinking every second. So that it feels more like a digital clock.

Is this something that would make sense incorporating?

Looking forward to your feedback.

**Comment by mineschan** [comment]
Hi @to83 

I considered that MZTimerLabel is not really a library to do what a clock does, but I may not add this feature. But your suggestion is a cool one. Thanks.

For now, you still have workaround for this feature. You may use a format like "HH mm" to setup MZTimerLabel, put a UILabel on top of it with a "colon" and setup a NSTimer fire every second to trigger it hidden status.


Cheers
