### ISSUE TITLE
关于时间设置颜色的问题

### ISSUE THREAD

**Issue by EasonGaoDevelop** [mineschan/MZTimerLabel#53]
遇到一个需求，显示倒计时，用了你的，时间部分的设置需要不同颜色字体，但是没有提供相关接口

**Comment by mineschan** [comment]
@EasonGaoDevelop 

謝謝你的提議，現在有接口可以改變某部份的字，顏色的接口還沒有，會研究一下

**Comment by mineschan** [comment]
To: @NosovPavel 

Thanks for your contribute before to let user change text in ranges. #53 is a request to have the possibility to change the text color in ranges too. Can you have a look and see if you can help adding this feature ?

**Comment by NosovPavel** [comment]
@mineschan Hi, i added this feature. @EasonGaoDevelop that is what you needed?
https://github.com/mineschan/MZTimerLabel/pull/54

**Comment by mineschan** [comment]
@NosovPavel Thanks! It works exactly like @EasonGaoDevelop wants.

@EasonGaoDevelop 請看看example 13 的實例代碼
