### ISSUE TITLE
HH:MM:SS Not showing as 12:MM:SS when countdown timer goes below 60 min.

### ISSUE THREAD

**Issue by Apptation** [mineschan/MZTimerLabel#57]
Hi, I'm new to using MZTimerLabel, and it's an awesome little utility. I'm not sure if this is an isolated issue with XCode7 and iOS9 or not:

I'm using a countdown timer, with the following settings:

labelTimer = [[MZTimerLabel alloc] initWithLabel:lblLine8 andTimerType:MZTimerLabelTypeTimer];
    [labelTimer setCountDownToDate:endDate];
labelTimer.timeFormat = @"hh:mm:ss";
labelTimer.resetTimerAfterFinish = NO;
labelTimer.delegate = self;
[labelTimer start];

Here's the issue:
When the endDate is over 1 hour ahead, then the labelTimer shows as e.g: 01:45:22, and can be seen counting down.

Then when the labelTimer drops from 01:00:00, it displays as 12:59:59 and shows counting down (but I would expect to see 00:59:59 and counting down).

If I manually set the countdown to less than one hour using: -(void)setCountDownTime:(NSTimeInterval)time, when the time format is: hh:mm:ss, then the label still shows as: 12:XX:XX

As a workaround, I've had to modify my code to check the value of the label timer using "- (NSTimeInterval)getTimeRemaining", and when it's > 1h, I set labelTimer.timeFormat = @"hh:mm:ss";
And when it's < 1h, I set labelTimer.timeFormat = @"mm:ss";

This sort of gets the job done, but it's not ideal.

Am I doing something wrong? I've checked over all the docs and the MZTimerLabel.h file to make sure I'm not missing anything. Maybe this is isolated to XCode7 / iOS9.

Thanks,

Chris

**Comment by mineschan** [comment]
Hi @Apptation 

It is just a very minor mistake, try to change the timeformat from  "hh" to "HH" then your problem will be solved!

Cheers,
MineS

**Comment by Apptation** [comment]
Thanks 😃 I thought I tried that, but I will give it a go.
Did I miss that somewhere in the documentation?

On Tue, Sep 29, 2015 at 1:23 AM, mineschan/MZTimerLabel
<reply@reply.github.com>
wrote:
Closed #57 [https://github.com/mineschan/MZTimerLabel/issues/57] .

—
Reply to this email directly or view it on GitHub
[https://github.com/mineschan/MZTimerLabel/issues/57#event-421497532] .[https://github.com/notifications/beacon/AGsyPpwtA4z4mOys6v50WYm2UBVAMzprks5o2hfLgaJpZM4GE2xU.gif]
