### ISSUE TITLE
`timeFormat` 屬性的問題

### ISSUE THREAD

**Issue by zhwayne** [mineschan/MZTimerLabel#64]
如果我像這樣指定倒計時的格式：
```
timeLabel.timeFormat = @"MM-dd HH:mm:ss";
```
那麼將會得到一個錯誤的結果：MM 和 dd 表示的值會多 1。

比如最後 3s 的倒計時應該是 00-00 00:00:03，結果卻是 01-01 00:00:03

**Comment by mineschan** [comment]
@zhwayne  謝謝你的回報，MZTimerLabel當初並沒有計劃支援日子的倒數／計時，所以於做法上沒有照顧到這個情況。

因為是使用`NSDateFormatter` 去轉換時間，月份和日是沒有「０」的。所以變成「１」是正確的結果。

如果真的需要月和日，我建議你可以使用delegate中的`-(void)timerLabel:(MZTimerLabel*)timerLabel countingTo:(NSTimeInterval)time timertype:(MZTimerLabelType)timerType;`去寫代碼計算。
