### ISSUE TITLE
customTextToDisplayAtTime called way too frequently

### ISSUE THREAD

**Issue by holgersindbaek** [mineschan/MZTimerLabel#71]
`customTextToDisplayAtTime` is getting called every 10 milliseconds or so in my app. Seems way to frequent for a timer where the smallest time I'm showing is seconds. Is there any way to change this?

**Comment by holgersindbaek** [comment]
All you have to do, is to change the value of "kDefaultFireIntervalHighUse".

**Comment by CavalcanteLeo** [comment]
how?

we can't change it, it is private a method

**Comment by holgersindbaek** [comment]
@CavalcanteLeo Fork the repo.

**Comment by CavalcanteLeo** [comment]
i will send a pull request later to change it
