### ISSUE TITLE
Problems setting up the number of days

### ISSUE THREAD

**Issue by iMaBiao** [mineschan/MZTimerLabel#72]
If I want to set the number of days, will be more one day

**Comment by CavalcanteLeo** [comment]
int second = (int)time  % 60;
        int minute = ((int)time / 60) % 60;
        int hours = ((int)time / 3600) % 24;
        int days = time / (3600 * 24);
        
        if (days > 0) {
            return [NSString stringWithFormat:@"%d : %02d : %02d : %02d",days,hours,minute,second];
    
       }  else if (hours > 0) {
            return [NSString stringWithFormat:@"%d : %02d : %02d",hours,minute,second];
     
      } else if (minute > 0) {
            return [NSString stringWithFormat:@"%d : %02d",minute,second];
        
      } else if (second > 0) {
            return [NSString stringWithFormat:@"%02d",second];

        } else {
            return nil;
        }

**Comment by mineschan** [comment]
@thanks @CavalcanteLeo

**Comment by mrtv** [comment]
Though the custom text solution works just fine, this is a real issue. I don't think it should be closed.
