### ISSUE TITLE
setCountDownTime

### ISSUE THREAD

**Issue by BadChoice** [mineschan/MZTimerLabel#77]
I found that when calling multiple `setCountDownTime` the counter is decreased faster than normal (a few seconds everytime it is called)

I need to do that since it is in a reusable cell, so everytime a cell is reloaded I need to set the right countdown time

I've been digging to find what makes it fail, and I can't find it..
Any solution?
Thanks!

**Comment by vimalrick** [comment]
Hi BadChoice, 
Have you found any workaround for this? 
I am facing the same issue

**Comment by BadChoice** [comment]
Yeah, I found out it wasn't it being called multiple times, but settings a negative time what caused the wrong behaviour,

hope it helps!
