### ISSUE TITLE
Add in HH field after "59:59"

### ISSUE THREAD

**Issue by BallerChan** [mineschan/MZTimerLabel#79]
I would like the label to have the format "mm:ss" while the stopwatch is under an hour but switch to "HH:mm:ss" once it hits that mark. I am using the _timerLabel:(MZTimerLabel *)timerLabel countingTo:(NSTimeInterval)time timertype:(MZTimerLabelType)timerType_  method to track how much time has passed, but I can't seem to reset the time format once the timer is running.

**Comment by BallerChan** [comment]
Turns out I was creating an infinite cycle.

**Comment by mineschan** [comment]
Yes, that's can solve your issue.
