### ISSUE TITLE
How i can invalidate timer

### ISSUE THREAD

**Issue by mhtranbn** [mineschan/MZTimerLabel#87]
How i can invalidate timer? Many thank for support great lib.

**Comment by jihongboo** [comment]
+1

**Comment by jihongboo** [comment]
@mhtranbn I read the code, fond out
```
- (void) removeFromSuperview {
    if (_timer) {
        [_timer invalidate];
        _timer = nil;
    }
    
    [super removeFromSuperview];
}
```
it means you have to call [removeFromSuperview] then the timer will invalidate, but your label will disappear too.

**Comment by mhtranbn** [comment]
thank @jihongboo! 
Nope, i cant use removeFromSuperview() of MZTimerLabel

**Comment by mineschan** [comment]
`pause` is invalidating the timer, could that help?

**Comment by mhtranbn** [comment]
yup, many thanks for support.

2017-10-27 15:53 GMT+07:00 MineS Chan <notifications@github.com>:
