### ISSUE TITLE
CountDown acts like a StopWatch

### ISSUE THREAD

**Issue by cmouline** [mineschan/MZTimerLabel#90]
Here's my code : 
            timer.setCountDownTime(180)
            timer.start()
            timer.timeFormat = "mm:ss"

What I get is a label starting at 03:00 but instead of decreasing, the time increase (03:01, 03:02 and so on). Did I miss something or is this, as I suspect, not the correct behavior ?

**Comment by mineschan** [comment]
Set the right type when you init the instance

**Comment by cmouline** [comment]
Great ! Works like a charm, I was initializing the label from storyboard that's why I didn't see that parameter.
